### ISSUE TITLE
(EPIC) Architecture and Infrastructure Setup

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#10]
EPIC- Theme:Need to create the environment for development
**Stories for Epic 10**
- [x] Setup Development server #15 
- [x] Setup Continuous Integration server #16 
- [x] Setup Database #17 
- [x] High Level Systems Architecture Diagram #91 
- [x] Define Data Model in MongoDB #102
- [x] Optimize setup and security of infrastructure for pilot
- [x] Setup pseudo production infrastructure
