### ISSUE TITLE
(EPIC) Write HMDA rules in spec

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#12]
Theme: Need to write the rules for the edit checks

Stories for Epic 12
- [x] Write rules for the syntactical edit checks #41
- [x] Write rules for the validity edit checks #42
- [x] Write rules for the quality edit checks #43
