### ISSUE TITLE
(EPIC) Lookup APIs

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#14]
EPIC API Lookups:  Theme: Need to get the data necessary to check certain edits from corresponding APIs.  Need to be able to comment on failed edits
**Stories for EPIC**
- [x] PIC- API Lookups.
- [x] Setup API baseline #104
- [x] Load API Data #107 closed 1/7/2015
- [x] Model and Load data models for use in lookups #153 
- [x] Determine if a control number is valid (SO25) #135 
- [x] Determine if Metro Area is on the RespondentPanel (Q595) #136 
- [x] Determine if a Tax ID is the same as last year (Q012) #137 
- [x] Determine if loan applications is within ±20% of the previous year's (Q011) #138 
- [x] Determine if total loans is valid for Fannie Mae (Q070) #139 
- [x] Determine if total loans is valid for Ginnie Mae FHA loans (Q071) #140 
- [x] Determine if number of home purchase loans is valid (Q075) #141 
- [x] Determine if number of refinance loans is valid (Q076) #142 
- [x] Determine if a metroArea is a valid MSA/MD (V280) #143 
- [x] Determine if MSA/MD, state, and county codes do not = a valid combination (V290) #144 
- [x] Determine if a census tract is valid (V300) #145 
- [x] Determine if the combination of State/county/Census tract is valid (Q029) #146 
- [x] Determine if the MSA/MD, County, and Census tract are valid for a Non-Depository (Q030) #147 
- [x] Determine if State/County Codes are a valid combination (V295) #151 
- [x] Determine if % loans for Ginnie Mae year over year is within thresholds (Q072) #152 
- [x] Determine if bank is an MBS or nondepository institution (V110) #159
- [x] Timestamp must be later than timestamp on database (S013) #189
