### ISSUE TITLE
Display edit validation steps using a wizard navigation

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#155]
As a user
I want to see the steps involved in validating my HMDA file
So that I know what is coming next

### Tasks

- [x] Add wizard navigation to the wireframes @vizui 
- [x] Establish the controller and views for all of the summary pages that the navigation would use
- [x] Create a wizard service for maintaining the state of the user's navigation 
- [x] Create a directive for displaying the wizard navigation
- [ ] Allow service to set a status for each step. Status can be incomplete, complete or currently active. The default is incomplete.
- [x] Style the wizard navigation to look like the design group's approved comp

Child of #6
