### ISSUE TITLE
User can select the year of their filing

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#19]
Child of Epic #3

As a user	I want to select the filing year for my edit checking
so that I can edit test HMDA files from previous years and the current filing year in case I need to check a previous year's file using the same interface

**Given** that I have prepared my HMDA filing 
  And given that I am ready to test my HMDA data for edit failures
**When** I go to upload my HMDA data for file checking
**Then** I want to be able to choose the year of the HMDA data I am checking from the current year that we have a rule set available back to 2013

A/C
- For pilot, drop down contains 2013 and 2014

- [x] Develop UI wireframe for user selecting the filing year (previously #61) @vizui 
- [x] Implement UI for user selecting the filing year (previously #62) @poorgeek 
- [x] Implement API to return years with rule specification available (previously #63) @linuxbozo
- [x] Implement header and footer (Previously #92)
- [x] Select File year function (previously #105)

**Comment by LinuxBozo** [comment]
Closed out as part of Sprint 3 delivery
