### ISSUE TITLE
Confirm the selected file is a HMDA formatted file

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#24]
EPIC #3  Theme: Need the ability to verify the structure of the file

As a user	I want to be notified if the file I have selected to edit check is not a HMDA file
so that I know right away that I have selected the wrong type of file or that my file is in the wrong format for the edit checking

**Given** that I am on the file selection site
**When** I select a file for the HMDA edit checking system
**Then** I am notified if the format of the data does not conform to the HMDA data file specifications	

Story Tasks
- [x] Design UI to alert user when selected file is not a HMDA formatted file (previously #74) @vizui 
- [x] Implement UI to alert user when selected file is not a HMDA formatted file (previously #75) @poorgeek
- [x] Verify fields in HMDA file are valid type (previously #90) @doelleri
