### ISSUE TITLE
Documentation of Application

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#251]
This EPIC covers the required handover documentation for the HMDA Pilot project

Stories for this EPIC
- [x] Define documentation deliverables, provide samples/templates and obtain CFPB approval  #252 
- [x] Develop Required System Documentation #303
- [x] Document End User Guide for HMDA Pilot @Paul
- [x] Document Release Notes - describing features of the HMDA Pilot Application
- [x] Update Gate doc with: Use of SauceLabs for testing, updated Prod server specs, Node version,

**Comment by pkaplan** [comment]
closed 5/18/15
