### ISSUE TITLE
Add coveralls.io to each project for tracking code coverage

### ISSUE THREAD

**Issue by LinuxBozo** [cfpb/hmda-pilot#294]
As the HMDA Pilot Team, I want to be able to see code coverage metrics in Coveralls.io.

 - [x] Add coveralls.io processing to each project
  - [x] hmda-pilot
  - [x] hmda-rule-engine
  - [x] hmda-edit-check-api
  - [x] hmda-rule-spec
 - [x] Add coveralls and travis build status badge to each README
  - [x] hmda-pilot
  - [x] hmda-rule-engine
  - [x] hmda-edit-check-api
  - [x] hmda-rule-spec
