### ISSUE TITLE
(EPIC) File and Year selection

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#3]
EPIC File Selection Themes
Need to be able to check my HMDA data before filing
Need the ability to rerun the edit checks on my HMDA data if there is a problem
Need the ability to verify the structure of the file

**Stories for Epic**
- [x] Users can select an  HMDA data file from their local machine #20
- [x] User can select the year of their filing #19
- [x] Ability to rerun the edit checks on a corrected HMDA data file #22
- [x] Verify the HMDA data file matches the year selected by the user #23 
- [x] Confirm the selected file is an HMDA formatted file #24

**Comment by poorgeek** [comment]
All current tasks have been completed.
