### ISSUE TITLE
Pick the reason why a Macro quality edit failed

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#35]
Child of EPIC #8 
As a user	I want to be able to pick the reason for why a macro quality edit failed from a drop-down list
So I can provide the processor with a more standardized explanation for why the edit failed when required

**Given** that the edits are run against my HMDA file 
**And** that a quality or macro failure was found on the HMDA filing
**When** I come to a failure record in the detailed edit report that requires a comment
**Then** a drop down menu should appear for me to pick the reason the failure occurred	

Acceptance Criteria
Each row inside the detailed quality and macro edit reports has a button to verify that a financial institution has checked that the information provided is correct as-is and a drop down box appears to the right of verify that allows the user to make a selection from a drop down to identify why the edit failed (for instance, bought a new company, divested a company, etc.).

**Tasks for story**
- [x] Import list of reasons from spreadsheet
- [x] User can save and continue on to the next error in the list until they reach the end
- [x] Macro error is listed as verified in the summary once a reason has been associated with it
