### ISSUE TITLE
Verify a failed Quality or Macro Quality edit

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#37]
Child of EPIC #8 (EPIC) Correction response – Verify, Verify Comment, Q595, Q29 

As a user I want to be able to check "verified" for a specific edit failures
so I can communicate that I have verified the edit in my mortgage system

**Given** that I am viewing a quality or macro failure report
**When** I have confirmed that the record with the error is correct as is
**Then** I click the 'Verify' button corresponding to a specific failure record in the detailed edit report
and **Then** the selected failure record is marked as 'Verified'

Acceptance Criteria
When I view a quality or macro failure report, I can see a verify button on each error record's row and I am able to click on the verify button after I have determined that the error is correct as is. Once I click on the verify button then the record is marked as verified.

**Tasks for Story**
- [x] User can save and continue on to the next error in the list until they reach the end
- [x] Verify checkbox is disabled until the user is navigates to the last page of error data
- [x] Quality error is listed as verified in the summary once it has been checked off

**Comment by poorgeek** [comment]
Had a good discussion during our 2/2 designer meeting about the interaction for some of the buttons that appear on this page, as well as the comments in #35. We've scheduled a meeting for 2/5 to discuss those changes and the ramifications. Should be able to task out this story following that meeting.
