### ISSUE TITLE
Write rules for the quality edit checks 

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#43]
Child of (EPIC) Write HMDA rules in spec #12
As CFPB HMDA
We want to define the rules that govern quality edits using our spec language
So that we have a machine readable version of the quality Edits

Given a defined spec language
When I define the quality edits
Then the resulting rule set is machine readable
And validates against the spec definition
And the quality edit checks match the currently approved definition

Tasks for Story
- [x] Write rule language for quality edits for 2014 #85 
- [x] Write rule language for quality edits for 2013 #84 
- [x] Write rule language for macro quality edits for 2013 #86
- [x] Write rule language for macro quality edits for 2014 #87
