### ISSUE TITLE
Generating test data

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#45]
Child of Epic Pilot Data #44 

- [x] Generate test data to fail syntactical edits #54
- [x] Generate test data to fail validity edits #55
- [x] Generate test data to fail quality edits #56
- [x] Generate test data to fail file selection parsing #57
- [x] Generate test data to fail year selection #58
