### ISSUE TITLE
(EPIC) Rule Engine Implementation

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#46]
This EPIC covers stories required to implement a rule engine

**Given** HMDA data file
**And** a year
**And** a validation type
**When** submitted
**Then** a JSON response is returned using a defined error schema

**Stories of EPIC 46** 
- [x] Parsing the rule spec  #51
- [x] Running the business logic of the rule spec #52
- [x] Second wave of NON-API support functions #185
- [x] Run syntactical edit checks #27
- [x] Run validity edit checks #31
- [x] Run quality Edit checks #32 
- [x] Engine support for initial identified api custom 'call' conditions #83
- [x] Design error schema #99 completed 1/5/15
