### ISSUE TITLE
Running the business logic of the rule spec 

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#52]
Child of EPIC #46 Rule Engine Implementation

As a HMDA pilot system,
I want to validate a rule against a HMDA data file

**Given** rules are parsed into an abstract syntax tree or similar internal representation
**And** a HMDA file has been identified, validated and loaded into an internal JSON structure
**When** a rule needs to be processed
**Then** the rule as defined in the internal representation is executed against the internal JSON representation of the HMDA data file
**And** failed edit checks are recorded

Tasks for Story
- [x] Engine support for initial identified non-api custom 'call' conditions (previously #76)
- [x] Execute rules and return error json (previously #110) @stevejameskent 1/14/15
- [x] Engine API endpoint functions @stevejameskent 1/15/15
- [x] Engine support for 'formatting' conditions (previously #77)
- [x] Engine support for 'numeric' conditions (previously #78)
- [x] Engine support for 'string' conditions ([previously #79)
- [x] Engine support for 'boolean' conditions (previously #80)
- [x]  Engine support for 'list' conditions (previously #81)
- [x] Rule Spec API methods (previously #106)

**Comment by cladana** [comment]
This has been broken down into multiple stories as it was too large.

**Comment by cladana** [comment]
Closed out as part of Sprint 2 delivery
