### ISSUE TITLE
(EPIC) Edit Summary

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#6]
EPIC:  Edit Summary (previously Dashboard)- Theme: Need to be able to receive a report of the data I ran the edits against. Display of edit results at a high level (passes/fails, categories)

**Stories under Epic 6**
- [x] Display edit validation steps using a wizard navigation #155 
- [x] View a high level report of the syntactical/validity edit results (previously #28)
- [x] View a high level report of the quality/macro edits results (previously #93)
