### ISSUE TITLE
(EPIC) Loan level edit report detail

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#7]
EPIC 7 Loan Level edit report detail: Theme: Need to be able to receive a report of the data I ran the edits against. Detailed report of the LARs that failed for a particular edit (ex: Q029, S010, etc.) and edit type (syntactical, validity, quality) 

**Stories for EPIC**
- [x] Display loan level edit report for Syntactical or Validity edits (previously #29)
- [x] Display Quality Edit report (previously #30)
- [x] Display Macro Quality Edit report (previously #33)
