### ISSUE TITLE
Create Independent SQL-based Validator

### ISSUE THREAD

**Issue by psalaz** [cfpb/hmda-pilot#71]
Child of Epic Pilot Data #44 
- [x] Parse and load .dat data into SQL database #66 
- [x] Implement syntactical edits in SQL #67 
- [x] Implement validity edits in SQL #68  
- [x] Implement quality edits in SQL #69 
- [x] Generate report of SQL-based edit check failures #70
