### ISSUE TITLE
(EPIC) Correction response – Verify, Verify Comment, Q595, Q29

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#8]
Epic 8:  Theme: Need the ability to comment on failed edits (verify and picklist)

**Stories for EPIC**
- [x] Pick the reason why a quality or macro edit failed #35 
- [x] Verify all failed quality or macro quality edits of the same type #36 This effort canceled, wireframes were reworked. 
- [x] Verify a single failed quality or macro edit #37
